# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        
# Publish a TAG on Github. (Manual workflow)
name: Bedy90 - Riot Module - Deploy (Alpha)

on:   
  # release:
  #   types: [published]

  # Manual action
  workflow_dispatch:

permissions:
   contents: read
   packages: write  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    # Setup .npmrc file to publish to npm
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
         # Defaults to the user or organization that owns the workflow file
        scope: '@bedy90'
  
    - name: Configure npm for GitHub Packages
      run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

    - name: Install Typescript
      run: npm install typescript@5.8.3 -g
      
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build:tsup_pack

    - name: Generator prod package
      run: npm run build:package

    - uses: JS-DevTools/npm-publish@v3
      id : "publishTag"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"
        tag: alpha
        package: ./build

    - if: ${{ steps.publishTag.outputs.type }}
      run: echo "Version ${{ steps.publishTag.outputs.version }} has published !"