# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        
# --------------------------------------
# Debugging
# --------------------------------------
#     - name: Debugging with ssh
#      # You may pin to the exact commit or the version.
#       uses: lhotari/action-upterm@v1
# --------------------------------------

name: RiotModule Test Coverage

on:
  pull_request:
    branches:
    - rework/syncPattern
    
  release:
    types: [created, edited]
    branches:
    - rework/syncPattern 

  # Manual action
  workflow_dispatch:
  
env:
     Riot_APIDevKey: ${{ secrets.RIOT_APIDEVKEY }}

permissions:
   pull-requests: write
   packages: write
    # deployments
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestEnv

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1000
   
    - name: Fetch base
      run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1000
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Typescript
      run: npm install typescript@4.8.4 -g
      
    - name: Install dependencies
      run: npm ci

    - name: Run Test Coverage
      run: npm run test:ts_json_coverage 

#     - name: Upload coverage artifact
#       uses: actions/upload-artifact@v2
#       with:
#           name: test-coverage-output
#           path: coverageJson

#     - name: Download coverage artifact
#       uses: actions/download-artifact@v2
#       with:
#           path: artifacts
          
    # https://github.com/marketplace/actions/report-nyc-coverage
    - name: Report NYC coverage
      if: ${{ github.event_name == 'pull_request' }}
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
      with:
        # Path to coverage file generated by "nyc report".
        coverage_file: "coverageJson/coverage-summary.json"
        comment_template_file: "comment-template.md"

    - name: Publish on SSH
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "coverage/**"
        target: '/home/bedybot-docker/shared/coverage/www/'
