# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: RiotModule test2

on:
  # Manual action
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
     #   cache: 'npm'
        
    - name: Install Typescript
      run: npm install typescript@4.8.4 -g
      
    # - name: node version
    #  run: node -v
      
    # - name: npm version
    #  run: npm -v
      
    # - name: tsc version
    #  run: tsc -v  
      
    # - name: ls
    #  run: ls **
      
    - name: Install dependencies
      run: npm ci
      
    - name: ls depenci
      run: ls **
    #  run: npm install --only=dev
    
    # - name: Debugging with ssh
    #  # You may pin to the exact commit or the version.
    #  uses: lhotari/action-upterm@v1
              
#    - run: npm run build --if-present
    - run: npm run test:ts_run
